### ISSUE TITLE
 bash build.sh is giving error  "No package 'PETSc' found"

### ISSUE THREAD

**Issue by sumaiyadabeer** [ligmg/ligmg#1]
Steps to reproduces: 
1: clone the repo.
2: cd ligmg
3: bash build.sh

Expected Output: Configuring should be completed.

Actual output: Configuring incomplete.
![Screenshot from 2022-01-05 18-31-03](https://user-images.githubusercontent.com/45242496/148222347-15ae7501-5c95-4857-8125-97673ec22c8e.png)

**Comment by jedbrown** [comment]
Hi, you'll need to install PETSc (https://petsc.org) and export `PETSC_DIR` (and `PETSC_ARCH` if using an in-place build).

> PETSc will not be downloaded, so ensure that it is installed and `PETSC_DIR` and `PETSC_ARCH` are set.

**Comment by jedbrown** [comment]
Please let us know if this doesn't work for you. Also, if the README can state this more clearly.

**Comment by sumaiyadabeer** [comment]
Thanks @jedbrown
