### ISSUE TITLE
libmpi_cxx.so: undefined reference to `opal_uses_threads'

### ISSUE THREAD

**Issue by sumaiyadabeer** [ligmg/ligmg#2]
There was an issue with the installation of MPICH with PETSc so I installed it with the option -download-openmpi (with manually setting the Open MPI 2.1.1 which is installed inmy system too ) . I am getting the following error while building the ./build.sh of ligmg. make command is giving the error.

Error: 
[100%] Linking CXX executable bin/ligmg
/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to `opal_uses_threads'
collect2: error: ld returned 1 exit status
CMakeFiles/ligmg.dir/build.make:118: recipe for target 'bin/ligmg' failed
make[2]: *** [bin/ligmg] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/ligmg.dir/all' failed
make[1]: *** [CMakeFiles/ligmg.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

![Screenshot from 2022-01-16 20-10-06](https://user-images.githubusercontent.com/45242496/149664739-559cff95-93e5-44de-b26f-697635658163.png)

**Comment by jedbrown** [comment]
If you used `--download-openmpi`, then this system library should never be referenced. You can run `make -C build VERBOSE=1` so the CMake build prints its full command line. I suspect you are either using system wrappers or otherwise explicitly reference the system Open MPI, which conflicts with the one you told PETSc to build and use. They need to match.

**Comment by sumaiyadabeer** [comment]
Full command is: /usr/bin/c++ -O2 -g -DNDEBUG -pthread CMakeFiles/ligmg.dir/src/main.cpp.o CMakeFiles/ligmg.dir/src/OptionParser.cpp.o -o bin/ligmg  -Wl,-rpath,/home/sumaiya/petsc/arch-linux-cxx-debug/lib:/usr/lib/x86_64-linux-gnu/openmpi/lib ../third_party/CombBLAS/build/libCombBLAS.a /usr/lib/gcc/x86_64-linux-gnu/5/libgomp.so -lpthread /home/sumaiya/petsc/arch-linux-cxx-debug/lib/libpetsc.so /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so /usr/lib/libmpi.so 
![Screenshot from 2022-01-17 16-07-07](https://user-images.githubusercontent.com/45242496/149754392-a32f4c27-4043-4ccb-85d2-8ffe3f16a207.png)

Also there is no "libmpi_cxx.so" in petsc home. I have compiled petsc with "./configure --with-cc=gcc --with-cxx=g++ --with-fc=0 --download-f2cblaslapack=1 --download-openmpi"

**Comment by jedbrown** [comment]
Which MPI was used for CombBLAS? The problem is mixing two MPI implementations. You should check your environment and trace the issue back. To fix, you either need everything to use system MPI or for all MPI-using dependencies to use the Open MPI you had PETSc build.

**Comment by sumaiyadabeer** [comment]
Yes.. able to do it with system MPI. Openmpi v4.2.1, built petsc with flapack and rest was same as instructed in build.sh
